GET http://backendlumen.com HTTP/1.1
####
GET http://backendlumen.com/cep/02472100 HTTP/1.1
####
GET http://backendlumen.com/cep HTTP/1.1
####
GET http://backendlumen.com/historico HTTP/1.1
####
POST  http://backendlumen.com/historico/cadastrar HTTP/1.1
Content-Type: application/json

{
  "cep": "01001-000",
  "logradouro": "Praça da Sé",
  "complemento": "lado ímpar",
  "unidade": "",
  "bairro": "Sé",
  "localidade": "São Paulo",
  "uf": "SP",
  "ibge": "3550308",
  "gia": "1004",
  "ddd": "11",
  "siafi": "7107"
}